### ISSUE TITLE
[Question] Audio - understanding memory 

### ISSUE THREAD

**Issue by mantielero** [vapoursynth/vapoursynth#1050]
I made [https://github.com/mantielero/VapourSynth.nim](VapourSynth.nim], which is a wrapper for the Nim programming language. I am trying to update to API4. I am struggling with the audio. I don't know C++, so I am struggling to understand how to get the audio from the frames.

My understanding:
1. I get a VSnode that contain an audio node.
2. The node contains a number of frames.
3. The frame contains a number of channels.
4. I get pointer to each channel with `getReadPtr`.
5. The number of samples by means of `getFrameLength`
6. I understand that those samples go one after the other. Something like:
```
c1 c1 c1 ..... c1  xxxxxxxxxx c2 c2 c2 ....c2
```
7. The `bitsPerSample` indicate precisely that.

Is it like this?

**Comment by myrsloik** [comment]
Yes. That's it.

**Comment by mantielero** [comment]
Thanks for the confirmation. Furthermore, when I play a file in mplayer, I get:
```txt
AUDIO: 44100 Hz, 2 ch, s16le,
```
The info that I get using VapourSynth is:
```
VSAudioInfoObj:
  format: (sampletype: 1, bitspersample: 32, bytespersample: 4, numchannels: 2, channellayout: 3)
  sampleRate: 44100
  numSamples: 1854720
  numFrames:  604
```

Regarding the 4 bytes per sample: is this because there are 2 channels and it uses 2 bytes per sample in each channel? I would say no due to [this](https://github.com/vapoursynth/vapoursynth/blob/634e4d99d22ca38d37642762dce158647e320b37/src/vspipe/vspipe.cpp#L277).

Right now I am just trying to get the audio out the same as the audio in, but I am struggling with that.

Being the original wav file `s16le` I understand I should reinterpret as `uint16`, shouldn't I?
